apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headscale-tls
  namespace: headscale-operator
spec:
  dnsNames:
    - headscale.domain.com
  secretName: headscale-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: headscale-db
  namespace: headscale-operator
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: false
  storage:
    size: 1Gi

---
apiVersion: headscale.juliamertz.dev/v1
kind: Headscale
metadata:
  name: example
  namespace: headscale-operator
spec:
  tls:
    existingSecret: headscale-tls

  config:
    server_url: https://headscale.domain.com:30443
    tls_cert_path: /etc/headscale/tls/tls.crt
    tls_key_path: /etc/headscale/tls/tls.key
    policy:
      path: "/etc/headscale/acl.json"
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
    derp:
      server:
        enabled: true
        region_id: 999
        region_code: "hetzner"
        region_name: "Hetzner"
        stun_listen_addr: "0.0.0.0:3478"
        private_key_path: /var/lib/headscale/derp_server_private.key
      urls: []
      auto_update_enabled: false
    dns:
      override_local_dns: true
      base_domain: headscale.local
      magic_dns: true
      nameservers:
        global:
          - 1.1.1.1
          - 8.8.8.8

  deployment:
    env:
      - name: HEADSCALE_DATABASE_TYPE
        value: postgres
      - name: HEADSCALE_DATABASE_POSTGRES_HOST
        valueFrom:
          secretKeyRef:
            name: headscale-db-app
            key: host
      - name: HEADSCALE_DATABASE_POSTGRES_NAME
        valueFrom:
          secretKeyRef:
            name: headscale-db-app
            key: dbname
      - name: HEADSCALE_DATABASE_POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: headscale-db-app
            key: username
      - name: HEADSCALE_DATABASE_POSTGRES_PASS
        valueFrom:
          secretKeyRef:
            name: headscale-db-app
            key: password

